CREATE TABLE AMEX (
ID INTEGER NOT NULL,
ISSUING_NETWORK VARCHAR(1024),
CARD_NUMBER VARCHAR(1024),
PRIMARY KEY (ID)
);

CREATE TABLE DINERS_CLUB (
ID INTEGER NOT NULL,
ISSUING_NETWORK VARCHAR(1024),
CARD_NUMBER VARCHAR(1024),
PRIMARY KEY (ID)
);

CREATE TABLE DISCOVER (
ID INTEGER NOT NULL,
ISSUING_NETWORK VARCHAR(1024),
CARD_NUMBER VARCHAR(1024),
PRIMARY KEY (ID)
);

CREATE TABLE JCB (
ID INTEGER NOT NULL,
ISSUING_NETWORK VARCHAR(1024),
CARD_NUMBER VARCHAR(1024),
PRIMARY KEY (ID)
);

CREATE TABLE MASTER_CARD (
ID INTEGER NOT NULL,
ISSUING_NETWORK VARCHAR(1024),
CARD_NUMBER VARCHAR(1024),
PRIMARY KEY (ID)
);

CREATE TABLE VISA (
ID INTEGER NOT NULL,
ISSUING_NETWORK VARCHAR(1024),
CARD_NUMBER VARCHAR(1024),
PRIMARY KEY (ID)
);

CREATE TABLE VOYAGER (
ID INTEGER NOT NULL,
ISSUING_NETWORK VARCHAR(1024),
CARD_NUMBER VARCHAR(1024),
PRIMARY KEY (ID)
);